services:
  hass:
    image: homeassistant/home-assistant
    ports:
      - '8123:8123'
    volumes:
      - ./custom_component:/config/custom_components/tokyo_gas
  tokyo_gas_scraper:
    build:
      context: addon
      args:
#        BUILD_FROM: ghcr.io/home-assistant/aarch64-base:latest # RPi
        BUILD_FROM: ghcr.io/home-assistant/amd64-base:latest # Mac
    environment:
      - TZ=Asia/Tokyo
    ports:
      - '8000:8000'
