name: Tokyo Gas Scraper
description: Login to Tokyo Gas and scrape electricity usage
version: 0.0.0
slug: tokyo_gas_scraper
init: false
arch:
  - aarch64
startup: application
boot: auto
ports:
  8000/tcp: 8000
options: {}
schema: {}
